backend:
  name: git-gateway
  branch: main

media_folder: "admin/uploads" # REQUIRED: Path in repo where media will be stored
public_folder: "/uploads"     # REQUIRED: Path used in src attributes for media

collections:
  - name: "job_posts"
    label: "Job Posts"
    files:
      - label: "Job Data"
        name: "job_data"
        file: "admin/data.json"
        format: "json"
        fields:
          - label: "Job Listings"
            name: "jobs_list"
            widget: "list"
            summary: "{{fields.title}} | {{fields.company}}"
            fields:
              - { label: "Job Title", name: "title", widget: "string" }
              - { label: "Company Name", name: "company", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Application Deadline", name: "deadline", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD.MM.YYYY", time_format: false }
              - { label: "Job Type", name: "type", widget: "select", options: ["Government Job", "Private Job"] }
              - { label: "Full Job Description", name: "description", widget: "markdown" }
              - { label: "Application URL (Optional)", name: "url", widget: "string", required: false }
